In [4]:
import numpy as np
  
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
  
print("Enter the entries in a single line (separated by space): ")
  
entries = list(map(int, input().split()))
  
#For printing the matrix
matrix = np.array(entries).reshape(R, C)
print(matrix)

#Checking valid cell
def valid_cell(matrix, is_checked, row, col) :
    rows_num = len(matrix)
    cols_num = len(matrix[0])

    if (row < 0 or row >= rows_num 
        or col < 0 or col >= cols_num
        or is_checked[row][col] 
        or matrix[row][col] == 0) :
        return False
    return True

#Finding island tree
def search_island_tree(matrix, is_checked, row, col) :
    rows_num = len(matrix)
    cols_num = len(matrix[0])
 
    is_checked[row][col] = True
 
    for  i in range(-1, 2):
        for  j in range(-1, 2):
            is_valid_cell = valid_cell(matrix, is_checked, row+i, col+j)
            if (is_valid_cell) :
                search_island_tree(matrix, is_checked, row+i, col+j)

#Finding number of islands
def find_num_of_islands(matrix) :
    rows_num = len(matrix)
    cols_num = len(matrix[0])
    is_checked = [ [False for x in range(cols_num)] for x in range(rows_num)]
    count = 0
    for  i in range(0, rows_num):
        for  j in range(0, cols_num):
            if (matrix[i][j] == 1 and not is_checked[i][j]) :
                search_island_tree(matrix, is_checked, i, j)
                count += 1
             
    print("Number of islands:",count)
    
find_num_of_islands(matrix)


Enter the number of rows:5
Enter the number of columns:5
Enter the entries in a single line (separated by space): 
1 0 0 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 0 0 1
[[1 0 0 0 1]
 [1 0 0 1 1]
 [0 0 0 1 0]
 [0 0 1 0 1]
 [1 0 0 0 1]]
Number of islands: 3
